name: Django Music Publisher test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    
    steps:
    - uses: actions/checkout@v1
    - name: Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt coverage coveralls
    - name: Test
      run: |
        coverage run manage.py test 
